```{r}
library(tidyverse)
library(lessR)
library(infer)
```

```{r}
test.score= c(88,83,83,85,94,88,91,96,89,83,81,80,84,89,83,79)
```

```{r}
test.score %>% 
  as_tibble() %>% 
  rep_sample_n(size=30, replace = T, reps = 10) %>% 
  Histogram(value, density = T, data=.)
```

```{r}
dist=
  test.score %>% 
  as_tibble() %>% 
  specify(response = value) %>% 
  generate(reps=1000, type="bootstrap") %>% 
  calculate(stat="mean")
dist
```



```{r}
ci_95=
  dist %>% 
  get_ci(level=0.95)
ci_95
```

```{r}
dist %>% 
  visualise() + 
  shade_ci(ci_95, fill="lightblue", color="orange", size=1, alpha=0.5)
```

```{r}
book= c(8,1,10,15,15,10,5,19,20,9,10)
alpha.2= qt(0.025,10) %>% abs(.)

mean(book)-alpha.2*sd(book)/sqrt(length(book))
mean(book)+alpha.2*sd(book)/sqrt(length(book))
```


```{r}
dist=
  book %>% 
  as_tibble() %>% 
  specify(response = value) %>% 
  generate(reps=100000, type="bootstrap") %>% 
  calculate(stat="mean")
dist
```

```{r}
ci_95=
  dist %>% 
  get_ci(level=0.95)
ci_95
```

```{r}
dist %>% 
  visualise() + 
  shade_ci(ci_95, fill="lightblue", color="orange", size=1, alpha=0.5)
```

```{r}
qchisq(0.025,39)
qchisq(1-0.025, 39)
```

























































